# **DATA PREPROCESSING :**

# **IMPORT LIBRARY :**

In [ ]:
import matplotlib.pyplot as mtp

In [ ]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

# **IMPORT DATASET :**

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/datapre.csv')

In [ ]:
dataset

COUNTRY   AGE    SALARY COMPLETED
0      India  35.0  340000.0       yes
1    Denmark  39.0  320000.0        no
2   Malaysia  45.0  200000.0       yes
3      India  34.0       NaN       yes
4   Malaysia  23.0  560000.0        no
5    Denmark  49.0       NaN        no
6      India   NaN  290000.0       yes
7    Denmark  25.0  150000.0        no
8   Malaysia  48.0  360000.0        no
9    Denmark  35.0  570000.0       yes
10         y   NaN       NaN       NaN

In [ ]:
dataset.head()

COUNTRY   AGE    SALARY COMPLETED
0     India  35.0  340000.0       yes
1   Denmark  39.0  320000.0        no
2  Malaysia  45.0  200000.0       yes
3     India  34.0       NaN       yes
4  Malaysia  23.0  560000.0        no

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   COUNTRY    11 non-null     object 
 1   AGE        9 non-null      float64
 2   SALARY     8 non-null      float64
 3   COMPLETED  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 480.0+ bytes


In [ ]:
dataset_encoded = pd.get_dummies(dataset, columns=['COUNTRY', 'COMPLETED'])

In [ ]:
X = dataset_encoded.iloc[:, :-1].values

y = dataset_encoded.iloc[:, -1].values


In [ ]:
print("FEATURES (X):", X)

FEATURES (X): [[35.0 340000.0 False True False False False]
 [39.0 320000.0 True False False False True]
 [45.0 200000.0 False False True False False]
 [34.0 nan False True False False False]
 [23.0 560000.0 False False True False True]
 [49.0 nan True False False False True]
 [nan 290000.0 False True False False False]
 [25.0 150000.0 True False False False True]
 [48.0 360000.0 False False True False True]
 [35.0 570000.0 True False False False False]
 [nan nan False False False True False]]


In [ ]:
print("TARGET (y):", y)

TARGET (y): [ True False  True  True False False  True False False  True False]


In [ ]:
dataset.isnull().sum()

COUNTRY      0
AGE          2
SALARY       3
COMPLETED    1
dtype: int64

# **FILLING  MISSING VALUES :**

In [ ]:
data2 = dataset.copy()

In [ ]:
print("Before:",dataset.shape)

dataset.dropna(inplace=True)

print("After:",dataset.shape)

Before: (11, 4)
After: (7, 4)


In [ ]:
X

array([[35.0, 340000.0, False, True, False, False, False],
       [39.0, 320000.0, True, False, False, False, True],
       [45.0, 200000.0, False, False, True, False, False],
       [34.0, nan, False, True, False, False, False],
       [23.0, 560000.0, False, False, True, False, True],
       [49.0, nan, True, False, False, False, True],
       [nan, 290000.0, False, True, False, False, False],
       [25.0, 150000.0, True, False, False, False, True],
       [48.0, 360000.0, False, False, True, False, True],
       [35.0, 570000.0, True, False, False, False, False],
       [nan, nan, False, False, False, True, False]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[[35.0 340000.0 0.0 True False False False]
 [39.0 320000.0 1.0 False False False True]
 [45.0 200000.0 0.0 False True False False]
 [34.0 348750.0 0.0 True False False False]
 [23.0 560000.0 0.0 False True False True]
 [49.0 348750.0 1.0 False False False True]
 [nan 290000.0 0.0 True False False False]
 [25.0 150000.0 1.0 False False False True]
 [48.0 360000.0 0.0 False True False True]
 [35.0 570000.0 1.0 False False False False]
 [nan 348750.0 0.0 False False True False]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 1 1 0 0 1 0 0 1 0]


# **TRAIN TEST SPLIT :**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[35.0 570000.0 1.0 False False False False]
 [39.0 320000.0 1.0 False False False True]
 [nan 290000.0 0.0 True False False False]
 [35.0 340000.0 0.0 True False False False]
 [25.0 150000.0 1.0 False False False True]
 [nan 348750.0 0.0 False False True False]
 [48.0 360000.0 0.0 False True False True]
 [49.0 348750.0 1.0 False False False True]]


In [ ]:
print(X_test)

[[45.0 200000.0 0.0 False True False False]
 [34.0 348750.0 0.0 True False False False]
 [23.0 560000.0 0.0 False True False True]]


In [ ]:
print(y_train)

[1 0 1 1 0 0 0 0]


In [ ]:
print(y_test)

[1 1 0]


# **NORMALISATION :**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
X_train[:, 3:] = mm.fit_transform(X_train[:, 3:])
X_test[:, 3:] = mm.transform(X_test[:, 3:])

In [ ]:
print(X_train[:, 3:])

[[0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 1.0]
 [1.0 0.0 0.0 0.0]
 [1.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 1.0]
 [0.0 0.0 1.0 0.0]
 [0.0 1.0 0.0 1.0]
 [0.0 0.0 0.0 1.0]]


In [ ]:
print(X_test[:, 3:])

[[0.0 1.0 0.0 0.0]
 [1.0 0.0 0.0 0.0]
 [0.0 1.0 0.0 1.0]]


# **STANDARDIZATION :**

In [ ]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 3:] = sta.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sta.transform(X_test[:, 3:])

In [ ]:
print(X_train[:, 3:])

[[-0.5773502691896258 -0.3779644730092272 -0.3779644730092272 -1.0]
 [-0.5773502691896258 -0.3779644730092272 -0.3779644730092272 1.0]
 [1.7320508075688774 -0.3779644730092272 -0.3779644730092272 -1.0]
 [1.7320508075688774 -0.3779644730092272 -0.3779644730092272 -1.0]
 [-0.5773502691896258 -0.3779644730092272 -0.3779644730092272 1.0]
 [-0.5773502691896258 -0.3779644730092272 2.6457513110645903 -1.0]
 [-0.5773502691896258 2.6457513110645903 -0.3779644730092272 1.0]
 [-0.5773502691896258 -0.3779644730092272 -0.3779644730092272 1.0]]


In [ ]:
print(X_test[:, 3:])

[[-0.5773502691896258 2.6457513110645903 -0.3779644730092272 -1.0]
 [1.7320508075688774 -0.3779644730092272 -0.3779644730092272 -1.0]
 [-0.5773502691896258 2.6457513110645903 -0.3779644730092272 1.0]]
